### ISSUE TITLE
Exercise 3 launch.json modifications

### ISSUE THREAD

**Issue by jordan0day** [reverentgeek/electron-workshop#1]
I had to add the following fields to my launch.json configuration to have the app launch and display for a VS Code debug session:

```javascript
"configurations": [
    {
      ...
      "runtimeArgs": ["."],
      "protocol": "legacy"
    }
  ]
```

Without `"protocol": "legacy"`, electron wouldn't launch at all, and without `"runtimeArgs": ["."]`, the shell would launch and I could hit breakpoints in `main.js`, but the actual window containing my "Hello, Electron!" bits would not display.

My environment is OS X 10.12.5, Node 8.2.1, VS Code 1.14.2

**Comment by reverentgeek** [comment]
I updated the config examples. Thanks!
