### ISSUE TITLE
Excercise 3 may require changing protocol from legacy to inspector

### ISSUE THREAD

**Issue by jpierson** [reverentgeek/electron-workshop#3]
Initially after attempting to start the debugger via `F5` in VSCode for Exercise 3 I got the following error.

> Cannot connect to runtime via 'legacy' protocol; try to use 'inspector' protocol.

This ran me into https://github.com/Microsoft/vscode/issues/21104 which suggested trying using the `inspector` protocol as show below. Switching this made things work for me. My guess is that the default launch templates were probably installed along with electron or VSCode and are just outdated. 

If somebody could find the original source of the templates it would be worth a followup PR to correct this and perhaps get inspector set as the default. Until then perhaps updating the exercise to show this manual change may help others if they are running into this issue.

```diff
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Electron Main",
            "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron",
            "program": "${workspaceFolder}/main.js",
-           "protocol": "legacy"
+           "protocol": "inspector"
        }
    ]
}
```

For sake of tracking I'm running Windows 10 and Node v7.9.0.

**Comment by reverentgeek** [comment]
Updated. Thank you!
